### ISSUE TITLE
Windows Defender has detected a trojan in your package

### ISSUE THREAD

**Issue by coolfarmer** [Marciel032/FarmingSimulatorTelemetry#15]
Windows Defender has detected a trojan in your package: Trojan:Win32/Sabsik.FL.A!ml
Defender automatically deleted the .zip.

You should run a scan on your computer. Maybe your files are infected...

**Comment by Marciel032** [comment]
Probably understood as a virus, due to the IO operations that are executed in the pipeline. 

I will check how to resolve this. Thanks.

**Comment by coolfarmer** [comment]
ClientDemo.zip was a zip containing the already compiled version?

**Comment by Marciel032** [comment]
Yes, he is not that important. It was just the app to test telemetry. The mods continue into release.
