### ISSUE TITLE
License / 6DOF

### ISSUE THREAD

**Issue by marcelomanzo** [Marciel032/FarmingSimulatorTelemetry#22]
Hi Marciel, the license has not be defined? Can I use your mod in a commercial product?

Did you have any luck with the 6DOF?
https://forum.giants-software.com/viewtopic.php?f=895&t=185941&p=1456946&hilit=roll+pitch#p1456946

**Comment by Marciel032** [comment]
Hi

Happy new year! = )

Yes, you can use for commercial propose, without problem.
I will be happy if you reference this mod in your product, but it is not mandatory.
I put the MIT license in the project, thank you for ask it.

About the 6DOF... Actualy i work in a analogic dashboard for a motion platform, so, the 6DOF does't the main priority. But i will work in it comming months.

**Comment by marcelomanzo** [comment]
Thanks a lot, once you add the yaw, roll, pitch and the gforces (lateral, longitudinal, e vertical acceleration), I will certainly incorporate in my product and give you the proper credit.

Glad to hear that you had choose MIT.

Thanks!

**Comment by marcelomanzo** [comment]
What does the getRotation(vehicle.rootNode) returns to you? A quarternion?

**Comment by Marciel032** [comment]
Here is the documentation about "getRotation" function:

[https://gdn.giants-software.com/documentation_scripting_fs19.php?version=engine&category=26&function=313](https://gdn.giants-software.com/documentation_scripting_fs19.php?version=engine&category=26&function=313)

**Comment by marcelomanzo** [comment]
Hint:
https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=41&class=446

The ?_rot are the yaw,roll and pitch.

<html>
<body>


local paramsXZ = self.highPrecisionPositionSynchronization and g_currentMission.vehicleXZPosHighPrecisionCompressionParams or g_currentMission.vehicleXZPosCompressionParams
--
1003 | local paramsY = self.highPrecisionPositionSynchronization and g_currentMission.vehicleYPosHighPrecisionCompressionParams or g_currentMission.vehicleYPosCompressionParams
1004 | for i=1, table.getn(self.components) do
1005 | local component = self.components[i]
1006 | local x = NetworkUtil.readCompressedWorldPosition(streamId, paramsXZ)
1007 | local y = NetworkUtil.readCompressedWorldPosition(streamId, paramsY)
1008 | local z = NetworkUtil.readCompressedWorldPosition(streamId, paramsXZ)
1009 | local x_rot = NetworkUtil.readCompressedAngle(streamId)
1010 | local y_rot = NetworkUtil.readCompressedAngle(streamId)
1011 | local z_rot = NetworkUtil.readCompressedAngle(streamId)
1012 |  
1013 | local qx,qy,qz,qw = mathEulerToQuaternion(x_rot,y_rot,z_rot)
1014 | self:setWorldPositionQuaternion(x,y,z, qx,qy,qz,qw, i, true)
1015 |  
1016 | component.networkInterpolators.position:setPosition(x,y,z)
1017 | component.networkInterpolators.quaternion:setQuaternion(qx,qy,qz,qw)
1018 | end


</body>
</html>

**Comment by marcelomanzo** [comment]
But this is from the world, we need from the vehicle

**Comment by Marciel032** [comment]
https://gdn.giants-software.com/documentation_scripting_fs19.php?version=script&category=41&class=446#writeStream6375

In the "writeStream" method, is used "getWorldRotation", then this value is read in "readStream".

Maybe using "getRotation", return the local values.


<html>
<body>


for i=1, table.getn(self.components) do
--
1076 | local component = self.components[i]
1077 | local x,y,z = getWorldTranslation(component.node)
1078 | local x_rot,y_rot,z_rot = getWorldRotation(component.node)
1079 | NetworkUtil.writeCompressedWorldPosition(streamId, x, paramsXZ)
1080 | NetworkUtil.writeCompressedWorldPosition(streamId, y, paramsY)
1081 | NetworkUtil.writeCompressedWorldPosition(streamId, z, paramsXZ)
1082 | NetworkUtil.writeCompressedAngle(streamId, x_rot)
1083 | NetworkUtil.writeCompressedAngle(streamId, y_rot)
1084 | NetworkUtil.writeCompressedAngle(streamId, z_rot)
1085 | end


</body>
</html>
