### ISSUE TITLE
What and how

### ISSUE THREAD

**Issue by OlaHaldor** [Marciel032/FarmingSimulatorTelemetry#23]
Hi, I was given a link to this project, and while not being a programmer, I wonder how and where I can use this data? 
I have an ipad and have found SimHub Dashboard. It works wonders, and their telemetry mod gives me only so much, while yours seem to be adding a lot more of what I'm interested in.

Do you think your mod can be combined, or replace the one from SimHub Dashboard?

**Comment by Marciel032** [comment]
Hi, this mod was developed thinking of other developers, who can use it in their own projects, building interfaces similar to SimHub.

As I'm developing an analog dashboard for games, and hadn't found a way to get the game data, I decided to implement it and leave it open for others to use.

From what I know about SimHub, it is possible to change the mod that is available for them, and add the information you need, but for that you need to know a little programming. Maybe if you talk to the SimHub developer, he can integrate this mod into the project. I am open to assisting in this process.

**Comment by OlaHaldor** [comment]
Excellent, thanks for replying. I've forwarded a link to them on their discord. :)

**Comment by Marciel032** [comment]
No problem, I'm happy to help.
