### ISSUE TITLE
How to add new data

### ISSUE THREAD

**Issue by LOWEL97** [Marciel032/FarmingSimulatorTelemetry#25]
How can I add new data receiving from the game? I mean something like gearbox type (CVX, Powershift, manual etc.) and vehicle type (harvester, tractor, truck etc.).
Sorry, but I'm new in C# programming but I've some experience with C on MCU boards.

**Comment by Marciel032** [comment]
1 - In the lua script, you will need add the requerid property in "FSTelemetry" object. To find the value from vehicle, you need to read de documentation from the giants software.
2 - In the c# client, you need to add a property in "FSTelemetry" class, with same name that you add in lua script before.
